import Head from 'next/head'
import styles from '../styles/Home.module.css'
//import {GetETHBalance} from '../JS/local_web3'

//import Script from 'next/script'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>


        {/* 
        <div> 
          <button onClick={GetETHBalance}>GetETHBalance</button>
        </div>
        
        <script>
          CONTRACT_ADDRESS = "0x8Fac2e25DFF0B248A19A66Ae8D530613c8Ff670B"
        </script>
        */}

        {/* 
        <script type="module" src="./direct/GetETHBalance.js"></script>
        */}



        {/* */}
        <div
          className='mintButton'
          data_address='0x9234E442ED4Df8BB53eA2d05311241d8ec522499'
        >
        Balance ...
        </div>
        <script async type="module" src="./direct/GetETHBalance.js"></script>
        



      </main>
    </div>
  )
}
